# frozen_string_literal: true

source "https://rubygems.org"

gem "base64"
gem "bigdecimal"
gem "kramdown-parser-gfm"
gem "logger"
gem "fiddle"

# gem "rails"
# gem "jekyll"
gem "just-the-docs"

group :jekyll_plugins do
  gem "jekyll-sitemap"
  gem "jekyll-feed"
  gem "jekyll-seo-tag"
  gem "jekyll-remote-theme"
end

gem "github-pages", group: :jekyll_plugins